[package]
name = "scribe-pty"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
scribe-common.workspace = true
scribe-image-decode.workspace = true
alacritty_terminal.workspace = true
tokio.workspace = true
vte.workspace = true
tracing.workspace = true
rustix.workspace = true
